# Generated by Django 3.1.7 on 2021-03-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='laboratoryDetails',
            fields=[
                ('Labid', models.AutoField(primary_key=True, serialize=False)),
                ('labname', models.CharField(max_length=50)),
                ('emailid', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('labaddress', models.TextField()),
                ('Contact_no', models.CharField(max_length=10)),
                ('DoctorName', models.CharField(max_length=20)),
                ('DoctorDegree', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30, null=True)),
                ('LabOpenTime', models.TimeField()),
                ('LabCloseTime', models.TimeField()),
            ],
            options={
                'db_table': 'LaboratoryDetail',
            },
        ),
    ]
